name: Release

on: push

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    name: Get a working Release.
    outputs:
      output_1: ${{ steps.gen_output.outputs.output_1 }}
    steps:
      - name: Whereami
        run: pwd
      - name: List Files
        run: ls
      - name: Create Zip For release.
        run: zip -r release.zip *
          
