on: push

jobs:
  release:
    runs-on: ubuntu-latest
    name: Get a working Release.
    steps:
      - name: Create Zip For release.
  # You may pin to the exact commit or the version.
  # uses: darshitsri/zip-release@1b834d476c94810a45eca807618beb94650feb75
        uses: darshitsri/zip-release@v3
        with:
    # Filename for archive
          filename: release.zip # default is release.zip
    # Base path for archive files
          path: . # optional, default is .
    # Working directory before zipping
          directory: . # optional, default is .
          type: zip
          
