name: Release

on: push

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    name: Get a working Release.
    outputs:
      output_1: ${{ steps.gen_output.outputs.output_1 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Create Zip
        run: zip -r lhroot.zip ./*
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: lhroot Release
          path: ./lhroot.zip
          
