name: Upload To Release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
    # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: lhroot Release
    # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          path: .
    # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
          github-token: ${{ secret.GITHUB_TOKEN }}
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
